include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  plugins:
    - custom_lint

linter:
  rules:
    prefer_relative_imports: true
    sort_pub_dependencies: true
