include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
  
  plugins:
    - custom_lint

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_positional_boolean_parameters: false
    missing_whitespace_between_adjacent_strings: false
    public_member_api_docs: false
