name: reading
description: A new Flutter project.
publish_to: "none"
version: 1.0.0-alpha+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  easy_mask: ^2.0.1
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.6
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  go_router: ^12.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  image_picker: ^1.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  path_provider: ^2.1.0
  riverpod_annotation: ^2.1.1
  smooth_page_indicator: ^1.1.0
  unicons: ^2.1.1
  vector_graphics: ^1.1.6

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.5.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.3.3
  vector_graphics_compiler: ^1.1.6
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/compiled/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/app_icons/android.png
  image_path_ios: assets/app_icons/ios.png
