name: reading
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.6
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  go_router: ^8.0.5
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  riverpod_annotation: ^2.1.1
  transparent_image: ^2.0.1
  unicons: ^2.1.1
  vector_graphics: ^1.1.6

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  vector_graphics_compiler: ^1.1.6
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/compiled/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/app-icons/android.png
  image_path_ios: assets/app-icons/ios.png
