name: reading
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.6
  flutter_svg: ^2.0.6
  vector_graphics: ^1.1.6
  unicons: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  vector_graphics_compiler: ^1.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/compiled/
    - assets/vectors/compiled/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/app-icons/android.png
  image_path_ios: assets/app-icons/ios.png
